[build]
  # Diretório base do projeto
  base = "igreja-app"
  
  # Comando de build
  command = "npm run build"
  
  # Diretório de saída
  publish = "dist"
  
  # Instalar dependências
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ."

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

# Configurações para SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers de segurança e cache
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# Configurações das Functions (Backend)
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Configurações de desenvolvimento
[dev]
  command = "npm run dev"
  port = 5173
  targetPort = 5173
  publish = "dist"
  autoLaunch = false